---
user:
  name: jrpotter
  email: jrpotter@github.io
ssh:
  private: $HOME/.ssh/id_ed25519
repos:
  local: $HOME/.homesync
  remote:
    name: origin
    branch: master
    url: "git@github.com:jrpotter/home-config.git"
packages:
  alacritty:
    - $HOME/.alacritty.yml
    - $HOME/.config/alacritty/alacritty.yml
    - $XDG_CONFIG_HOME/alacritty.yml
    - $XDG_CONFIG_HOME/alacritty/alacritty.yml
  bash:
    - $HOME/.bash_profile
    - $HOME/.bashrc
  home-manager:
    - $HOME/.config/nixpkgs/home.nix
  homesync:
    - $HOME/.homesync.yml
    - $HOME/.config/homesync/homesync.yml
    - $XDG_CONFIG_HOME/homesync.yml
    - $XDG_CONFIG_HOME/homesync/homesync.yml
  neovim:
    - $HOME/.config/nvim/init.vim
    - $XDG_CONFIG_HOME/nvim/init.vim
  termite:
    - $HOME/.config/termite/config
    - $XDG_CONFIG_HOME/termite/config
  tmux:
    - $HOME/.tmux.conf
