remote:
  owner: jrpotter
  name: home-config
packages:
  homesync:
    configs:
      - $HOME/.homesync.yml
      - $HOME/.config/homesync/homesync.yml
      - $XDG_CONFIG_HOME/homesync.yml
      - $XDG_CONFIG_HOME/homesync/homesync.yml
