---
local: ""
remote: "https://github.com/jrpotter/home-config.git"
packages:
  homesync:
    configs:
      - $HOME/.homesync.yml
      - $HOME/.config/homesync/homesync.yml
      - $XDG_CONFIG_HOME/homesync.yml
      - $XDG_CONFIG_HOME/homesync/homesync.yml
